[workspace]

members = [
    "simulator",
    "desim_benchmark",
    "desim_mpmc",
    "simrs_benchmark",
    "simulator_benchmark",
    "benchmarks",
    "simulator_nightly_benchmark",
    "simulator_nightly",
]

[profile.release]
lto = "fat"
codegen-units = 1